/**
 * Generate Angular environment files from .env files.
 * Run automatically before `npm start` or `npm run build`.
 * Usage: node scripts/generate-env.js
 */
const fs = require('fs');
const path = require('path');

const isProd = process.argv.includes('--prod') || process.env.NODE_ENV === 'production';

const envFile = isProd ? '.env.production' : '.env.local';
const outputFile = isProd ? 'environment.prod.ts' : 'environment.local.ts';
const productionFlag = isProd ? 'true' : 'false';

const envPath = path.resolve(process.cwd(), envFile);

if (!fs.existsSync(envPath)) {
  console.warn(`⚠️  ${envFile} not found. Using fallback values in environment.ts`);
  process.exit(0);
}

const envContent = fs.readFileSync(envPath, 'utf-8');
const envVars = {};

envContent.split('\n').forEach(line => {
  const [key, ...valueParts] = line.split('=');
  if (key && !key.startsWith('#') && valueParts.length > 0) {
    envVars[key.trim()] = valueParts.join('=').trim();
  }
});

const apiUrl = envVars.API_URL || '';

const outputContent = `/* This file is auto-generated by scripts/generate-env.js. Do NOT edit manually. */
export const environment = {
  production: ${productionFlag},
  apiUrl: '${apiUrl}',
};
`;

const outputPath = path.resolve(process.cwd(), 'src/environments', outputFile);
fs.writeFileSync(outputPath, outputContent, 'utf-8');

console.log(`✅ Generated ${outputPath} from ${envFile}`);

